//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Login.WS_Acceso {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_AccesoSoap", Namespace="http://cesion.org/")]
    public partial class WS_Acceso : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscarClienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_Acceso() {
            this.Url = global::Login.Properties.Settings.Default.Login_WS_Acceso_WS_Acceso;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuscarClienteCompletedEventHandler BuscarClienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cesion.org/BuscarCliente", RequestNamespace="http://cesion.org/", ResponseNamespace="http://cesion.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MENSAJERES_Type BuscarCliente(CABECERA_Type cabecera, DATOS_Type datosWC) {
            object[] results = this.Invoke("BuscarCliente", new object[] {
                        cabecera,
                        datosWC});
            return ((MENSAJERES_Type)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarClienteAsync(CABECERA_Type cabecera, DATOS_Type datosWC) {
            this.BuscarClienteAsync(cabecera, datosWC, null);
        }
        
        /// <remarks/>
        public void BuscarClienteAsync(CABECERA_Type cabecera, DATOS_Type datosWC, object userState) {
            if ((this.BuscarClienteOperationCompleted == null)) {
                this.BuscarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarClienteOperationCompleted);
            }
            this.InvokeAsync("BuscarCliente", new object[] {
                        cabecera,
                        datosWC}, this.BuscarClienteOperationCompleted, userState);
        }
        
        private void OnBuscarClienteOperationCompleted(object arg) {
            if ((this.BuscarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarClienteCompleted(this, new BuscarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb")]
    public partial class CABECERA_Type {
        
        private string aPP_CONSUMIDORAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string APP_CONSUMIDORA {
            get {
                return this.aPP_CONSUMIDORAField;
            }
            set {
                this.aPP_CONSUMIDORAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04001")]
    public partial class DATOSRes_Type {
        
        private string cliente_RucField;
        
        private string cliente_Cod_PartField;
        
        private string endPoint_Cli_Cone_xionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cliente_Ruc {
            get {
                return this.cliente_RucField;
            }
            set {
                this.cliente_RucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cliente_Cod_Part {
            get {
                return this.cliente_Cod_PartField;
            }
            set {
                this.cliente_Cod_PartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EndPoint_Cli_Cone_xion {
            get {
                return this.endPoint_Cli_Cone_xionField;
            }
            set {
                this.endPoint_Cli_Cone_xionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04001")]
    public partial class DETALLERes_Type {
        
        private DATOSRes_Type dATOSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DATOSRes_Type DATOS {
            get {
                return this.dATOSField;
            }
            set {
                this.dATOSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb")]
    public partial class CABECERARes_Type {
        
        private string aPP_CONSUMIDORAField;
        
        private string cOD_RESPUESTAField;
        
        private string dES_RESPUESTAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string APP_CONSUMIDORA {
            get {
                return this.aPP_CONSUMIDORAField;
            }
            set {
                this.aPP_CONSUMIDORAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_RESPUESTA {
            get {
                return this.cOD_RESPUESTAField;
            }
            set {
                this.cOD_RESPUESTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DES_RESPUESTA {
            get {
                return this.dES_RESPUESTAField;
            }
            set {
                this.dES_RESPUESTAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04001")]
    public partial class INTEGRACIONRES_Type {
        
        private CABECERARes_Type cABECERAField;
        
        private DETALLERes_Type dETALLEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CABECERARes_Type CABECERA {
            get {
                return this.cABECERAField;
            }
            set {
                this.cABECERAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DETALLERes_Type DETALLE {
            get {
                return this.dETALLEField;
            }
            set {
                this.dETALLEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04001")]
    public partial class MENSAJERES_Type {
        
        private INTEGRACIONRES_Type iNTEGRESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public INTEGRACIONRES_Type INTEGRES {
            get {
                return this.iNTEGRESField;
            }
            set {
                this.iNTEGRESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cavali.com.pe/ib/esb/srv04001")]
    public partial class DATOS_Type {
        
        private string dominioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dominio {
            get {
                return this.dominioField;
            }
            set {
                this.dominioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BuscarClienteCompletedEventHandler(object sender, BuscarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MENSAJERES_Type Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MENSAJERES_Type)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591